{% set name = "hpo-toolkit" %}
{% set version = "0.5.5.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b137d190539767f1daf5e9f51db78e79bb0a57ffa564d55714e4af2633764535

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.6
    - numpy >= 1.10

test:
  imports:
    - hpotk
  requires:
    - tox
    - setuptools
    - pip
  commands:
    - pip check
about:
  home: https://github.com/TheJacksonLaboratory/hpo-toolkit
  summary: 'A toolkit for working with Human Phenotype Ontology in Python'
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    Hpo-toolkit is a library for working with Human Phenotype Ontology and HPO annotation data in Python. 

extra:
  recipe-maintainers:
    - ielis
    - iimpulse
